### ISSUE TITLE
how to get map_keyframes and metadata in dict?

### ISSUE THREAD

**Issue by yxl502** [TranMinhThang123/VideoSearchCLIP#1]

**Comment by TranMinhThang123** [comment]
Thank you @yxl502 for the question, for the map_keyframes, it is extracted from video using [TransNet](https://github.com/soCzech/TransNetV2) and the dict is create base on map_keyframes, you can see [data_preparation.ipynb](https://github.com/TranMinhThang123/VideoSearchCLIP/blob/master/notebook/data_preparation.ipynb) for more detail
